version: '3'
services:
  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "5001:5001"
    environment:
      FLASK_ENV: development
  web:
    build: Web/
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development